//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCastingV2.DBlib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Annonce
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Annonce()
        {
            this.Candidatures = new HashSet<Candidature>();
        }
    
        public int ID_ANN { get; set; }
        public string Intitulée_ANN { get; set; }
        public System.DateTime Date_Pub_ANN { get; set; }
        public System.DateTime Date_Deb_ANN { get; set; }
        public Nullable<System.DateTime> Date_Fin_ANN { get; set; }
        public int IdContrat { get; set; }
        public int IdPro { get; set; }
        public int IdEmp { get; set; }
        public int IdVille { get; set; }
        public int IdMetier { get; set; }
    
        public virtual Contrat Contrat { get; set; }
        public virtual Employe Employe { get; set; }
        public virtual Metier Metier { get; set; }
        public virtual Professionnel Professionnel { get; set; }
        public virtual Ville Ville { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Candidature> Candidatures { get; set; }
    }
}
