//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCastingV2.DBlib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MegaCastingEntities : DbContext
    {
        public MegaCastingEntities()
            : base("name=MegaCastingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Annonce> Annonces { get; set; }
        public virtual DbSet<Artiste> Artistes { get; set; }
        public virtual DbSet<Candidature> Candidatures { get; set; }
        public virtual DbSet<Contrat> Contrats { get; set; }
        public virtual DbSet<Employe> Employes { get; set; }
        public virtual DbSet<Metier> Metiers { get; set; }
        public virtual DbSet<Professionnel> Professionnels { get; set; }
        public virtual DbSet<Statut> Statuts { get; set; }
        public virtual DbSet<Ville> Villes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
