//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCastingV2.DBlib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MegacastingEntities : DbContext
    {
        public MegacastingEntities()
            : base("name=MegacastingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Annonce> Annonce { get; set; }
        public virtual DbSet<Artiste> Artiste { get; set; }
        public virtual DbSet<Candidature> Candidature { get; set; }
        public virtual DbSet<Contrat> Contrat { get; set; }
        public virtual DbSet<Employe> Employe { get; set; }
        public virtual DbSet<Metier> Metier { get; set; }
        public virtual DbSet<Professionnel> Professionnel { get; set; }
        public virtual DbSet<Statut> Statut { get; set; }
        public virtual DbSet<Ville> Ville { get; set; }
    }
}
